[build]
  publish = "public"
  command = "npm run build"

[context.production]
  environment= { GATSBY_ALGOLIA_INDEX_PREFIX = "live_" }


[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"