[build]
  publish = "public"
  command = "npm run build"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build-preview"

[context.branch-deploy]
  command = "npm run build"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
