[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"

[context.production]
  environment= { GATSBY_ALGOLIA_INDEX_PREFIX = "live_" }

[context.deploy-preview]
  command = "npm run build-preview"
  environment = {DEV_ENVIRONMENT_VARIABLE_FILE = "false", ALGOLIA_ADMIN_KEY = "0", CTP_GITHUB_API_BUILD_TOKEN="0", CTP_GITHUB_API_BUILD_KEY="0"}

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"