version: 2.1

executors:
  main-executor:
    docker:
      - image: circleci/node:10.19.0
        environment:
          TZ: 'America/New_York'
    working_directory: /tmp

jobs:
  setup:
    executor: main-executor
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - run:
          name: setup
          command: 'npm run setup'
      - run:
          name: build
          command: 'npm run build:gatsby'
      - persist_to_workspace:
          root: workspace
          paths:
            - ./
  gatsby-test:
    executor: main-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: test
          command: 'npm run test'
  gatsby-lint:
    executor: main-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: lint
          command: 'npm run test:lint'
workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - gatsby-test:
          requires:
            - setup
      - gatsby-lint:
          requires:
            - setup
