version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - run:
          name: setup
          command: 'npm run setup'
      - run:
          name: build
          command: 'npm run build:gatsby'
      - run:
          name: test
          command: 'npm run test'
