version: 2.1
jobs:
  setup:
    docker:
      - image: circleci/node:10.19.0
        environment:
          TZ: 'America/New_York'
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - run:
          name: setup
          command: 'npm run setup'
      - run:
          name: build
          command: 'npm run build:gatsby'
  gatsby-test:
    steps:
      - run:
          name: test
          command: 'npm run test'
  gatsby-lint:
    steps:
      - checkout
      - run:
          name: install
          command: 'npm install'
      - run:
          name: lint
          command: 'npm run test:lint'
workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - gatsby-test
      - gatsby-lint
