name: Test deployed API
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Netlify
        uses: JakePartusch/wait-for-netlify-action@v1.2
        id: preview
        with:
          site_name: "upbeat-lovelace-3e9fff"
          max_timeout: 600

      - uses: actions/checkout@v1

      - name: Install
        run: npm install

      - name: Test
        env:
          JEST_COVID_API_HOST: ${{ steps.preview.outputs.url }}
        run: npm run test:api-header-test
