name: Sync
on:
  push:
    branches:
      - master

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.1.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "contentful-preview"
          PULL_REQUEST_TITLE: "chore: Sync Contentful preview branch [skip netlify]"
          PULL_REQUEST_BODY: "The `contentful-preview` branch is used for our content editors to have a space to preview content changes. This PR keeps that branch up to sync with master."