name: automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  update_test_snapshots:
    if: github.event.label.name == 'auto update test snapshots'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install
        run: npm install
      - name: Update test snapshots
        run: npm run test:update
      - name: Commit changes
        run: |
          git config --global user.email "website@covidtracking.com"
          git config --global user.name "CTP Test Update"
          git add ./src/__tests__/*
          git commit -m "Automatically updated test snapshots"
          git push origin HEAD